#!/bin/bash
# PreToolUse hook: Block edits to generated/fetched files that should never be hand-edited.
# - packages/math-*/build/    (WASM binaries fetched from HydraDX-wasm repo)
# - .papi/descriptors/        (generated by papi CLI from whitelist.ts)

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Math WASM builds — fetched artifacts, not source
if [[ "$FILE_PATH" == */packages/math-*/build/* ]]; then
  cat <<'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "math-*/build/ contains fetched WASM binaries from HydraDX-wasm repo. To update, modify scripts/build-math.mjs or the upstream repo."
  }
}
EOF
  exit 0
fi

# Papi generated descriptors
if [[ "$FILE_PATH" == */.papi/descriptors/* ]]; then
  cat <<'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": ".papi/descriptors/ is generated by papi CLI. Edit packages/descriptors/src/whitelist.ts instead, then run: cd packages/descriptors && npm run prebuild"
  }
}
EOF
  exit 0
fi

exit 0
