export enum ApiUrl {
  Local = 'ws://localhost:8000',
  Chopsticks = 'wss://chopsticks.rpc.hydration.cloud',
  Chopsticks_Node = 'ws://[::]:17777',
  Basilisk = 'wss://rpc.basilisk.cloud',
  Basilisk_UK = 'wss://basilisk-mainnet-rpc-07.basilisk.cloud',
  Basilisk_Rococo = 'wss://rococo-basilisk-rpc.hydration.dev',
  Basilisk_Rococo_UK = 'wss://rococo-basilisk-rpc04.hydration.dev',
  Basilisk_Rococo_CLOUD = 'wss://basilisk-rococo-rpc.play.hydration.cloud',
  Hydration = 'wss://hydration-rpc.n.dwellir.com',
  Nice = 'wss://rpc.nice.hydration.cloud',
  Lark1 = 'wss://1.lark.hydration.cloud',
  Lark2 = 'wss://2.lark.hydration.cloud',
  Lark3 = 'wss://3.lark.hydration.cloud',
}
