export const SNOWBRIDGE = [
  { inputs: [], name: 'AgentAlreadyExists', type: 'error' },
  { inputs: [], name: 'ShouldNotReachHere', type: 'error' },
  { inputs: [], name: 'InvalidNetwork', type: 'error' },
  { inputs: [], name: 'InvalidAsset', type: 'error' },
  { inputs: [], name: 'InsufficientGasLimit', type: 'error' },
  { inputs: [], name: 'InvalidCommand', type: 'error' },
  { inputs: [], name: 'InsufficientValue', type: 'error' },
  { inputs: [], name: 'ExceededMaximumValue', type: 'error' },
  { inputs: [], name: 'TooManyAssets', type: 'error' },
  {
    inputs: [],
    name: 'operatingMode',
    outputs: [{ internalType: 'enum OperatingMode', name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'agentID', type: 'bytes32' }],
    name: 'agentOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'agentID',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'agent',
        type: 'address',
      },
    ],
    name: 'AgentCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nonce',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'topic',
        type: 'bytes32',
      },
      { indexed: false, internalType: 'bool', name: 'success', type: 'bool' },
      {
        indexed: false,
        internalType: 'bytes32',
        name: 'rewardAddress',
        type: 'bytes32',
      },
    ],
    name: 'InboundMessageDispatched',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nonce',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'index',
        type: 'uint256',
      },
    ],
    name: 'CommandFailed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint64',
        name: 'nonce',
        type: 'uint64',
      },
      {
        components: [
          {
            internalType: 'address',
            name: 'origin',
            type: 'address',
          },
          {
            components: [
              { internalType: 'uint8', name: 'kind', type: 'uint8' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
            ],
            internalType: 'struct Asset[]',
            name: 'assets',
            type: 'tuple[]',
          },
          {
            components: [
              { internalType: 'uint8', name: 'kind', type: 'uint8' },
              { internalType: 'bytes', name: 'data', type: 'bytes' },
            ],
            internalType: 'struct Xcm',
            name: 'xcm',
            type: 'tuple',
          },
          {
            internalType: 'bytes',
            name: 'claimer',
            type: 'bytes',
          },
          {
            internalType: 'uint128',
            name: 'value',
            type: 'uint128',
          },
          {
            internalType: 'uint128',
            name: 'executionFee',
            type: 'uint128',
          },
          {
            internalType: 'uint128',
            name: 'relayerFee',
            type: 'uint128',
          },
        ],
        indexed: false,
        internalType: 'struct Payload',
        name: 'payload',
        type: 'tuple',
      },
    ],
    name: 'OutboundMessageAccepted',
    type: 'event',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'bytes32', name: 'origin', type: 'bytes32' },
          { internalType: 'uint64', name: 'nonce', type: 'uint64' },
          { internalType: 'bytes32', name: 'topic', type: 'bytes32' },
          {
            components: [
              { internalType: 'uint8', name: 'kind', type: 'uint8' },
              { internalType: 'uint64', name: 'gas', type: 'uint64' },
              { internalType: 'bytes', name: 'payload', type: 'bytes' },
            ],
            internalType: 'struct Command[]',
            name: 'commands',
            type: 'tuple[]',
          },
        ],
        internalType: 'struct InboundMessage',
        name: 'message',
        type: 'tuple',
      },
      { internalType: 'bytes32[]', name: 'leafProof', type: 'bytes32[]' },
      {
        components: [
          {
            components: [
              { internalType: 'bytes32', name: 'parentHash', type: 'bytes32' },
              { internalType: 'uint256', name: 'number', type: 'uint256' },
              { internalType: 'bytes32', name: 'stateRoot', type: 'bytes32' },
              {
                internalType: 'bytes32',
                name: 'extrinsicsRoot',
                type: 'bytes32',
              },
              {
                components: [
                  { internalType: 'uint256', name: 'kind', type: 'uint256' },
                  {
                    internalType: 'bytes4',
                    name: 'consensusEngineID',
                    type: 'bytes4',
                  },
                  { internalType: 'bytes', name: 'data', type: 'bytes' },
                ],
                internalType: 'struct Verification.DigestItem[]',
                name: 'digestItems',
                type: 'tuple[]',
              },
            ],
            internalType: 'struct Verification.ParachainHeader',
            name: 'header',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint256', name: 'pos', type: 'uint256' },
              { internalType: 'uint256', name: 'width', type: 'uint256' },
              { internalType: 'bytes32[]', name: 'proof', type: 'bytes32[]' },
            ],
            internalType: 'struct Verification.HeadProof',
            name: 'headProof',
            type: 'tuple',
          },
          {
            components: [
              { internalType: 'uint8', name: 'version', type: 'uint8' },
              { internalType: 'uint32', name: 'parentNumber', type: 'uint32' },
              { internalType: 'bytes32', name: 'parentHash', type: 'bytes32' },
              {
                internalType: 'uint64',
                name: 'nextAuthoritySetID',
                type: 'uint64',
              },
              {
                internalType: 'uint32',
                name: 'nextAuthoritySetLen',
                type: 'uint32',
              },
              {
                internalType: 'bytes32',
                name: 'nextAuthoritySetRoot',
                type: 'bytes32',
              },
            ],
            internalType: 'struct Verification.MMRLeafPartial',
            name: 'leafPartial',
            type: 'tuple',
          },
          { internalType: 'bytes32[]', name: 'leafProof', type: 'bytes32[]' },
          { internalType: 'uint256', name: 'leafProofOrder', type: 'uint256' },
        ],
        internalType: 'struct Verification.Proof',
        name: 'headerProof',
        type: 'tuple',
      },
      { internalType: 'bytes32', name: 'rewardAddress', type: 'bytes32' },
    ],
    name: 'v2_submit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes', name: 'xcm', type: 'bytes' },
      { internalType: 'bytes[]', name: 'assets', type: 'bytes[]' },
      { internalType: 'bytes', name: 'claimer', type: 'bytes' },
      { internalType: 'uint128', name: 'executionFee', type: 'uint128' },
      { internalType: 'uint128', name: 'relayerFee', type: 'uint128' },
    ],
    name: 'v2_sendMessage',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'token', type: 'address' },
      { internalType: 'uint8', name: 'network', type: 'uint8' },
      { internalType: 'uint128', name: 'executionFee', type: 'uint128' },
      { internalType: 'uint128', name: 'relayerFee', type: 'uint128' },
    ],
    name: 'v2_registerToken',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes32', name: 'id', type: 'bytes32' }],
    name: 'v2_createAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'v2_outboundNonce',
    outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint64', name: 'nonce', type: 'uint64' }],
    name: 'v2_isDispatched',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'isTokenRegistered',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
