import {
  HydrationWhitelistEntry,
  HubWhitelistEntry,
  WhitelistEntriesByChain,
} from '../.papi/descriptors';

const hydrationWhitelist: HydrationWhitelistEntry[] = [
  // runtime
  'api.AaveTradeExecutor.*',
  'api.CurrenciesApi.*',
  'api.EthereumRuntimeRPCApi.*',
  'api.EvmAccountsApi.*',
  'api.Metadata.*',
  // const
  'const.Aura.*',
  'const.Balances.*',
  'const.CircuitBreaker.*',
  'const.DCA.*',
  'const.DynamicFees.*',
  'const.HSM.*',
  'const.LBP.*',
  'const.Omnipool.*',
  'const.OmnipoolLiquidityMining.*',
  'const.OTC.*',
  'const.Referenda.*',
  'const.Stableswap.*',
  'const.Staking.*',
  'const.XYK.*',
  'const.XYKLiquidityMining.*',
  // event
  'event.EVM.Log',
  'event.Router.Executed',
  'event.Stableswap.*',
  // query
  'query.AssetRegistry.*',
  'query.Balances.*',
  'query.Bonds.*',
  'query.ConvictionVoting.*',
  'query.Democracy.*',
  'query.DynamicFees.*',
  'query.EmaOracle.*',
  'query.Ethereum.*',
  'query.HSM.*',
  'query.LBP.*',
  'query.MultiTransactionPayment.*',
  'query.Omnipool.*',
  'query.OmnipoolLiquidityMining.*',
  'query.OmnipoolWarehouseLM.*',
  'query.OTC.*',
  'query.ParachainSystem.ValidationData',
  'query.Referenda.*',
  'query.Referrals.*',
  'query.Stableswap.*',
  'query.Staking.*',
  'query.Timestamp.*',
  'query.Tokens.*',
  'query.Uniques.Account',
  'query.XYK.*',
  'query.XYKWarehouseLM.*',
  // tx
  'tx.ConvictionVoting.*',
  'tx.Currencies.*',
  'tx.DCA.*',
  'tx.Democracy.*',
  'tx.Dispatcher.*',
  'tx.EVM.*',
  'tx.EVMAccounts.*',
  'tx.MultiTransactionPayment.*',
  'tx.Omnipool.*',
  'tx.OmnipoolLiquidityMining.*',
  'tx.OTC.*',
  'tx.Referrals.*',
  'tx.Router.*',
  'tx.Stableswap.*',
  'tx.Staking.*',
  'tx.Tokens.*',
  'tx.Utility.*',
  'tx.XYK.*',
  'tx.XYKLiquidityMining.*',
];


const hubWhitelist: HubWhitelistEntry[] = [
  'query.ForeignAssets.*',
  'query.Assets.*',
  'api.AssetConversionApi.*',
  'tx.Assets.*',
];

export const whitelist: WhitelistEntriesByChain = {
  '*': [
    'api.DryRunApi.*',
    'api.XcmPaymentApi.*',
    'const.System.*',
    'query.System.*',
    'tx.PolkadotXcm.*',
  ],
  hydration: hydrationWhitelist,
  hub: hubWhitelist,
};
