import {
  HydrationWhitelistEntry,
  HydrationIceWhitelistEntry,
  HubWhitelistEntry,
  WhitelistEntriesByChain,
} from '../.papi/descriptors';

const hydrationWhitelist: HydrationWhitelistEntry[] = [
  // runtime
  'api.AaveTradeExecutor.*',
  'api.CurrenciesApi.*',
  'api.EthereumRuntimeRPCApi.*',
  'api.EvmAccountsApi.*',
  'api.Metadata.*',
  // const
  'const.Aura.*',
  'const.Balances.*',
  'const.CircuitBreaker.*',
  'const.DCA.*',
  'const.DynamicFees.*',
  'const.HSM.*',
  'const.LBP.*',
  'const.Multisig.*',
  'const.Omnipool.*',
  'const.OmnipoolLiquidityMining.*',
  'const.OTC.*',
  'const.Proxy.*',
  'const.Referenda.*',
  'const.Stableswap.*',
  'const.Staking.*',
  'const.XYK.*',
  'const.XYKLiquidityMining.*',
  // event
  'event.EVM.Log',
  'event.Proxy.PureCreated',
  'event.Router.Executed',
  'event.Stableswap.*',
  // query
  'query.AssetRegistry.*',
  'query.Balances.*',
  'query.Bonds.*',
  'query.CircuitBreaker.*',
  'query.ConvictionVoting.*',
  'query.Democracy.*',
  'query.DynamicFees.*',
  'query.EmaOracle.*',
  'query.Ethereum.*',
  'query.HSM.*',
  'query.Identity.*',
  'query.LBP.*',
  'query.MultiTransactionPayment.*',
  'query.Multisig.*',
  'query.Omnipool.*',
  'query.OmnipoolLiquidityMining.*',
  'query.OmnipoolWarehouseLM.*',
  'query.OTC.*',
  'query.ParachainSystem.ValidationData',
  'query.Proxy.*',
  'query.Referenda.*',
  'query.Referrals.*',
  'query.Stableswap.*',
  'query.Staking.*',
  'query.Timestamp.*',
  'query.Tokens.*',
  'query.Uniques.Account',
  'query.XYK.*',
  'query.XYKWarehouseLM.*',
  // tx
  'tx.ConvictionVoting.*',
  'tx.Currencies.*',
  'tx.DCA.*',
  'tx.Democracy.*',
  'tx.Dispatcher.*',
  'tx.EVM.*',
  'tx.EVMAccounts.*',
  'tx.MultiTransactionPayment.*',
  'tx.Multisig.*',
  'tx.Omnipool.*',
  'tx.OmnipoolLiquidityMining.*',
  'tx.OTC.*',
  'tx.Proxy.*',
  'tx.Referrals.*',
  'tx.Router.*',
  'tx.Stableswap.*',
  'tx.Staking.*',
  'tx.Tokens.*',
  'tx.Utility.*',
  'tx.XYK.*',
  'tx.XYKLiquidityMining.*',
];

const hydrationIceWhitelist: HydrationIceWhitelistEntry[] = [
  'const.ICE.*',
  'const.Intent.*',
  'query.ICE.*',
  'query.Intent.*',
  'tx.ICE.*',
  'tx.Intent.*',
];

const hubWhitelist: HubWhitelistEntry[] = [
  'query.ForeignAssets.*',
  'query.Assets.*',
  'api.AssetConversionApi.*',
  'tx.Assets.*',
  'tx.Balances.*',
];

export const whitelist: WhitelistEntriesByChain = {
  '*': [
    'api.DryRunApi.*',
    'api.XcmPaymentApi.*',
    'const.System.*',
    'query.System.*',
    'tx.PolkadotXcm.*',
  ],
  hydrationIce: hydrationIceWhitelist,
  hydrationNext: hydrationWhitelist,
  hydration: hydrationWhitelist,
  hub: hubWhitelist,
};
